version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    environment:
      - MONGODB_URI=${LOCAL_MONGODB_URI}   # Default to local DB
      - ATLAS_MONGODB_URI=${ATLAS_MONGODB_URI}
    command: sh -c "node scripts/seed.js && npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
    command: ["mongod", "--config", "/etc/mongod.conf"]

volumes:
  mongo-data:
