services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - MONGODB_URI=mongodb+srv://skillpro:htwskillpro2025@skillprocluster.agy7z8z.mongodb.net/skillprodb
    command: sh -c "node scripts/seed.js && npm run dev"

volumes:
  mongo-data:
