name: Next.js CI

on:
  push:
    branches: [dev, main, live]
  pull_request:
    branches: [dev, main, live]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skillpro

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm ci

      - run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./skillpro/coverage/lcov.info
          fail_ci_if_error: true

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./skillpro

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm ci

      - run: npm run build

      
